" .vimrc
set nocompatible                "Turn off compability mode with Vi, we don't need that anymore

" Pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Enable filetype stuff
filetype on
filetype plugin on
filetype plugin indent on

set cindent
set autoindent                  " Copy indent from current line when starting a new line.
set backspace=indent,eol,start  " makes backspace key more powerful.

set showmatch                   " do not show matching brackets by flickering
set incsearch                   " shows the match while typing
set hlsearch                    " highlight found searches
set smartcase                   " Turn of smart searching
set ignorecase                  " Search incase sensitive

set ruler                       " show line and column number
set wildmenu					" command line tab completion, more superior
set wildmode=list:full			" type :h wildmode for more info about list options
set history=1000                " Number of lines of command line history.

set noerrorbells                " No beeps
set gdefault                    " Use 'g' flag by default with :s/foo/bar/.
set number                      " Show line numbers

set ttyscroll=0                 " Turn off scrolling (this is faster).
set ttyfast                     " We have a fast terminal connection.
set showcmd                     " Show me what I'm typing
set showmode                    " Show current mode.
set encoding=utf-8              " Set default encoding to UTF-8
set autowrite                   " Automatically save before :next, :make etc.
set cmdheight=1                 " The commandbar height
set laststatus=2

set splitright                  " Split vertical windows right to the current windows
set splitbelow                  " Split horizontal windows below to the current windows
set noswapfile                  " Don't use swapfile
set clipboard+=unnamed

set mat=5                       " show matching brackets for 0.5 seconds
set wrap                        " word wrap
set lazyredraw                  " the screen will not be redrawn while executing macros, registers

" Prefer unix over windows over os9 formats
set fileformats=unix,dos,mac

" we don't want to edit these kind of files >.<
set wildignore=*.o,*.obj,*.bak,*.exe,*.so,*.la,*.out,*.pyc,*.swp

" C/C++ stuff, tabs are four columns wide. Each indentation level is one tab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab 

" Enable undo even if the file is closed
set undofile
set undodir=/tmp
set nobackup            " Dont create annoying backup files

"make vim save and load the folding of the document each time it loads"
""also places the cursor in the last place that it was left."
set viewdir=/tmp
"au BufWinLeave * mkview
"au VimEnter * silent! loadview

au BufWinLeave * silent! mkview
au BufWinEnter * silent! loadview


" -[ FileTypes ]-
" mail
autocmd FileType mail,human set formatoptions+=t textwidth=80

" markdown
autocmd FileType markdown set textwidth=80
autocmd FileType markdown set nocindent "Wraping fix for braces
autocmd FileType markdown set expandtab "Use spaces for tabs, a requirement by markdown
autocmd FileType markdown set shiftwidth=4

" Python stuff
" Wrap the lines to 80 characters
set tw=80
autocmd FileType python let python_highlight_all = 1
autocmd FileType python let python_slow_sync = 1
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType python set expandtab shiftwidth=4 softtabstop=4
autocmd FileType python set completeopt=menu
autocmd FileType python set expandtab              " Tabs are converted to spaces
" Open Tagbar only with python files. See Tagbar part for details.
autocmd FileType python nested :TagbarOpen

autocmd BufRead,BufNewFile *.go set filetype=go

" We'll use it for settings that should apply only to one OS (like Linux)
let os=substitute(system('uname'), '\n', '', '')

" Multibyte reading of utf-16
if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

""""""""""""""""""""
" Color and Syntax "
" ---------------- "
syntax enable                   " syntax formatting for languages
set background=dark

" Powerline
let g:Powerline_symbols = 'unicode'

"set t_Co=256                    " set to 256 color mode if the console supports it
"let g:solarized_termtrans=1
"let g:solarized_termcolors=256
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"
"colorscheme solarized "enable iterm2-solarized preset if you want to use it
 


" No toolbars, menu or scrollbars in the GUI
if has('gui')
    if os == 'Darwin' || os == 'Mac'
        set guifont=Source\ Code\ Pro:h13
        colorscheme solarized
    endif
	set vb t_vb=
	set guioptions-=m  "no menu
	set guioptions-=T  "no toolbar
	set guioptions-=l
	set guioptions-=L
	set guioptions-=r  "no scrollbar
	set guioptions-=R
end

"""""""""""""""""""""""""""""""""""""""""""""
" Mappings, key bindings for plugins, etc.. "
" ----------------------------------------- "
"
" I hate you F1, you are useless
" Act like a ESC
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>


" Better split switching
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" This comes first, because we have mappings that depend on leader
" With a map leader it's possible to do extra key combinations
" i.e: <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

set makeprg=make
set showfulltag

"This will look in the current directory for "tags", and work up the tree
"towards root until one is found. IOW, you can be anywhere in your source tree
"instead of just the root of it.
"set tags=./tags;/
"map <leader>s <C-W><C-I><CR>
"" Open the definition in a new tab
"map <leader>t :tab split<CR>:exec("tag ".expand("<cword>"))<CR>zz
"" Open the definition in a vertical split
"map <leader>v :vsp <CR>:exec("tag ".expand("<cword>"))<CR>zz

" ack spesific fixes
let g:ackprg="ack -H -a -i --column"
noremap <Leader>a :LAck! <cword><cr>

" Fast saving
nmap <leader>w :w!<cr>
nmap <leader>q :q!<cr>
nmap <leader>wq :wq!<cr>

" Save fold settings, open/close folds easily with spacebar
nnoremap <space> zz

" Move up and down on splitted lines (on small width screens)
map <Up> gk
map <Down> gj
map k gk
map j gj

" Make mouse middle click paste without formatting it
map <MouseMiddle> <Esc>"*p

" Autoclose Plugin
let g:AutoClosePairs_add = "\" '"  "add quotes to autoclose plugin

" Tagbar Plugin
if os == 'Linux'
	nmap <leader>b :TagbarToggle<CR>
	let g:tagbar_autofocus = 1
endif
" Only open Tagbar when used with python files. See python specific part for
" this.
"autocmd VimEnter * nested :TagbarToggle
"TODO: <F8> tagbar and TagbarToggle tagbar are not the same, take a look at it

" Open gundo
nnoremap <leader>g :GundoToggle<CR>

" Nerdtree plugin
nmap <leader>n :NERDTreeToggle <CR>
let NERDTreeChDirMode=1

if os == 'Darwin' || os == 'Mac'
	let g:NERDTreeDirArrows=0 " Fix a bug on mac
endif

let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$', '\.class$', 'pip-log\.txt$', '\.o$'] "

" open a NERDTree automatically when vim starts up if no files were specified
" TODO: this f*cks up when I use diff -u hede hodo | vi -
"   we should find a solution for this ;)
autocmd vimenter * if !argc() | NERDTree | endif

" Just go out in insert mode
imap jj <ESC>

" Search mappings: These will make it so that going to the next one in a
" search will center on the line it's found in.
map N Nzz
map n nzz

" Open help window always vertically
nmap zH :vert he

" Set working directory
nnoremap <leader>. :lcd %:p:h<CR>

" Automatically cd into the directory that the file is in
set autochdir

" save it with sudo again
nnoremap <leader>ss :w !sudo tee %<CR>  

" trim all whitespaces away
nnoremap <leader>W :%s/\s\+$//<cr>:let @/=''<CR>       

" Start scrolling three lines before the horizontal window border
set scrolloff=3

" Keep cursor in place when we join files
nnoremap J mzJ`z

" Act like D and C
nnoremap Y y$

" Ctrlp Plugin
"
let g:ctrlp_cmd = 'CtrlP'	    		" Open it in most recently used mode (the most important option everyone want!)
let g:ctrlp_working_path_mode = 'ra'	" search for nearest ancestor like .git, .hg, and the directory of the current file
let g:ctrlp_match_window_bottom = 1		" show the match window at the top of the screen:
let g:ctrlp_max_height = 10				" maxiumum height of match window
let g:ctrlp_switch_buffer = 'Et'		" jump to a file if its open already
let g:ctrlp_use_caching = 1				" enable caching
let g:ctrlp_cache_dir = $HOME.'/.cache/ctrlp' "cache dir
let g:ctrlp_show_hidden = 1				" show me dotfiles
let g:ctrlp_mruf_max = 250				" number of recently opened files

" vim-coffee-plugin
"
let g:coffee_compiler = '/usr/local/share/npm/bin/coffee'
let g:coffee_linter = '/usr/local/share/npm/bin/coffeelint'
let g:coffee_lint_options = '-f lint.json'

" -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*- "

""" python-mode plugin settings
"""
let g:pymode_lint_write = 1             " Enable pylint checking every save
let g:pymode_run_key = 'R'              " Set key 'R' for run python code

" Show documentation
let g:pymode_doc = 1                    " Load show documentation plugin
let g:pymode_doc_key = 'K'              " Key for show python documentation

" Run python code
let g:pymode_run = 1                    " Load run code plugin
let g:pymode_run_key = '<leader>r'      " Key for run python code

" Code checking 
let g:pymode_lint = 1                   " Load pylint code plugin

" Switch pylint, pyflakes, pep8, mccabe code-checkers
" Can have multiply values "pep8,pyflakes,mcccabe"
let g:pymode_lint_checker = "pyflakes,pep8,mccabe"

" Skip errors and warnings
" E.g. "E501,W002", "E2,W" (Skip all Warnings and Errors startswith E2) and etc
"let g:pymode_lint_ignore = "E501"

" Select errors and warnings
" E.g. "E4,W"
"let g:pymode_lint_select = ""

"let g:pymode_lint_onfly = 0           " Run linter on the fly

" Pylint configuration file
" If file not found use 'pylintrc' from python-mode plugin directory
let g:pymode_lint_config = "$HOME/.pylintrc"

"let g:pymode_lint_cwindow = 1           " Auto open cwindow if errors be finded
let g:pymode_lint_message = 1            " Show error message if cursor placed at the error line
let g:pymode_lint_jump = 0               " Auto jump on first error
let g:pymode_lint_hold = 0               " Hold cursor in current window when quickfix is open
let g:pymode_lint_signs = 1              " Place error signs
let g:pymode_lint_mccabe_complexity = 8  " Maximum allowed mccabe complexity

let g:pymode_lint_minheight = 3          " Minimal height of pylint error window
let g:pymode_lint_maxheight = 6          " Maximal height of pylint error window

""" ROPE PLUGIN in python-mode 
let g:pymode_rope = 1                    " Load rope plugin
let g:pymode_rope_auto_project = 1       " Auto create and open ropeproject
let g:pymode_rope_enable_autoimport = 1  " Enable autoimport
let g:pymode_rope_autoimport_generate = 1 " Auto generate global cache
let g:pymode_rope_autoimport_underlineds = 0 
let g:pymode_rope_codeassist_maxfixes = 10
let g:pymode_rope_sorted_completions = 1
let g:pymode_rope_extended_complete = 1
let g:pymode_rope_autoimport_modules = ["os","shutil","datetime"]
let g:pymode_rope_confirm_saving = 1
let g:pymode_rope_global_prefix = "<C-x>p"
let g:pymode_rope_local_prefix = "<C-c>r"
let g:pymode_rope_vim_completion = 1
let g:pymode_rope_guess_project = 1
let g:pymode_rope_goto_def_newwin = ""
let g:pymode_rope_always_show_complete_menu = 0

let g:pymode_utils_whitespaces = 1       " Autoremove unused whitespaces
let g:pymode_indent = 1                  " Enable pymode indentation

let g:pymode_virtualenv = 1              " Auto fix vim python paths if virtualenv enabled
let g:pymode_folding = 0                 " Do not automatically fold

" -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*- "
let g:Tlist_WinWidth = 50
let g:Tlist_Use_Right_Window = 1
"let g:Tlist_Auto_Open = 1
" Use F8 to cache  
nnoremap <silent> <F8> :TlistToggle<CR>  
